export const GIGS = [
  {
    title: "Fix Leaky Faucet",
    description: "Looking for someone to fix a leaky faucet in my kitchen.",
    price: 50,
    latitude: 28.6139,
    longitude: 77.2090,
    type: "HOUSEHOLD",
    status: "OPEN",
    giverId: "user-1-id",
  },
  {
    title: "Math Tutoring",
    description: "Need a math tutor for high school algebra. 2 hours per week.",
    price: 100,
    latitude: 28.6200,
    longitude: 77.2100,
    type: "EDUCATION",
    status: "OPEN",
    giverId: "user-2-id",
  },
  {
    title: "Dog Walking",
    description: "Walk my golden retriever for 30 minutes daily.",
    price: 25,
    latitude: 28.6175,
    longitude: 77.2300,
    type: "PET_CARE",
    status: "OPEN",
    giverId: "user-3-id",
  },
  {
    title: "Website Design",
    description: "Need a modern portfolio website built with React and Tailwind.",
    price: 500,
    latitude: 28.6000,
    longitude: 77.2000,
    type: "TECH",
    status: "OPEN",
    giverId: "user-4-id",
  },
  {
    title: "Grocery Delivery",
    description: "Pick up groceries and deliver them to my home.",
    price: 30,
    latitude: 28.6250,
    longitude: 77.2200,
    type: "ERRANDS",
    status: "OPEN",
    giverId: "user-5-id",
  },
  {
    title: "Lawn Mowing",
    description: "Mow my lawn for 2 hours.",
    price: 50,
    latitude: 28.6000,
    longitude: 77.2000,
    type: "GARDENING",
    status: "OPEN",
    giverId: "user-6-id",
  },
];

export const GigTypes = {
  HOUSEHOLD: "Household",
  EDUCATION: "Education",
  PET_CARE: "Pet Care",
  TECH: "Tech",
  ERRANDS: "Errands",
  GARDENING: "Gardening",
  CONSTRUCTION: "Construction",
  PLUMBING: "Plumbing",
  ELECTRICAL: "Electrical",
  CARPENTRY: "Carpentry",
  PAINTING: "Painting",
  CLEANING: "Cleaning",
  COOKING: "Cooking",
  DRIVING: "Driving",
  DELIVERY: "Delivery",
  SECURITY: "Security",
  MECHANIC: "Mechanic",
  WAREHOUSE: "Warehouse",
  MOVING: "Moving & Packing",
  FARMING: "Farming",
  BEAUTY: "Beauty & Grooming",
};



export const fakeNotifications = [
  {
    id: "1",
    userId: "user-123",
    title: "Gig Application Received",
    message: "John Doe applied for your Gardening gig.",
    type: "APPLICATION",
    read: false,
    createdAt: new Date("2025-08-22T14:32:00Z"),
  },
  {
    id: "2",
    userId: "user-123",
    title: "Application Accepted",
    message: "Your application for the Cleaning gig was accepted!",
    type: "STATUS_UPDATE",
    read: false,
    createdAt: new Date("2025-08-23T10:15:00Z"),
  },
  {
    id: "3",
    userId: "user-123",
    title: "Gig Completed",
    message: "Congrats! Your Cooking gig was marked as completed.",
    type: "GIG_UPDATE",
    read: true,
    createdAt: new Date("2025-08-20T08:50:00Z"),
  },
  {
    id: "4",
    userId: "user-123",
    title: "New Message",
    message: "Jane sent you a message about your Tutoring gig.",
    type: "MESSAGE",
    read: false,
    createdAt: new Date("2025-08-24T09:20:00Z"),
  },
  {
    id: "5",
    userId: "user-123",
    title: "Reminder",
    message: "Don’t forget your Delivery gig starts tomorrow!",
    type: "REMINDER",
    read: true,
    createdAt: new Date("2025-08-19T18:30:00Z"),
  },
];